<a href="https://colab.research.google.com/github/Zerberuz/evaluaciones_python_202520/blob/main/Evaluacion_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Evaluacion 3
## Python aplicado a la Ingeniería 202520
**Docente:** Miguel Ortiz

**Estudiante:** Camilo Ernesto Calderin Ogaza

**email:** camilo.calderino@upb.edu.co

**Fecha:** 10/09/2025

**Parte 1: Filtado de datos**

In [4]:
import  numpy as np

# Paso 1: Cargar los datos desde el archivo CSV
data= np.genfromtxt('GHI_Temp_Daily_Hourly_2024.csv', skip_header=True, delimiter=';')

# Paso 2: Verificar la carga de datos
print(data.shape)
print(f"Numero total de filas: {data.shape[0]}")
print(f"Numero total de columnas: {data.shape[1]}")

# Paso 3: Filtrar datos manualmente
year=2024
month=1
day=1

# Paso 4: Analizar los datos filtrados
filtered_data = data[(data[:, 0] == year) & (data[:, 1] == month) & (data[:, 2] == day)]
print(filtered_data)
print(len(filtered_data))
print(f"Se encontraron en la fecha {day}/{month}/{year} {len(filtered_data)} registros. ")

# Paso 5: Crear una función para filtrar datos por fecha
def filter_data_by_date(filepatch, year, month, day):
    data= np.genfromtxt(filepatch, skip_header=True, delimiter=';')
    datos_filtrados = data[(data[:, 0] == year) & (data[:, 1] == month) & (data[:, 2] == day)]
    if len(datos_filtrados) == 0:
        print(f"No se encontraron registros para la fecha {day}/{month}/{year}.")
    return datos_filtrados

# Paso 6: Guardar los datos filtrados en un nuevo archivo CSV
filename = f"filtered_data_{year}_{month:02d}_{day:02d}.csv"
with open(filename, "w") as file:
    file.write("Year,Month,Day,Hour,Temperature,GHI\n")
    for row in filtered_data:
        file.write(f"{int(row[0])},{int(row[1])},{int(row[2])},{int(row[3])},{row[4]:.2f},{row[5]:.2f}\n")
print(f"El archivo {filename} fue creado exitosamente")

# Paso 7: Verificación
result = filter_data_by_date('GHI_Temp_Daily_Hourly_2024.csv', 2024, 1, 1)
print("Archivo verificado - datos correctos")

# Paso 8: Agregar manejo de errores
def filter_data_by_date_improved(filepath, year, month, day):
    try:
        data = np.genfromtxt(filepath, skip_header=True, delimiter=',')
        datos_filtrados = data[(data[:, 0] == year) & (data[:, 1] == month) & (data[:, 2] == day)]
        if len(datos_filtrados) == 0:
            print("No se encontraron datos para la fecha especificada")
            return
        return

    except FileNotFoundError:
        print(f"No se encontró el archivo {filepath}")

    except IndexError:
        print("El archivo no tiene el formato esperado")

    except Exception as e:
        print("Error inesperado")
        print(f"Error específico: {e}")

# Paso 9: Agregar información adicional
def filter_data_final(filepath, year, month, day):
    #informacion de cuantos datos se cargaron
    try:
        data = np.genfromtxt(filepath, skip_header=True, delimiter=',')
        print(f"Se cargaron {len(data)} registros")
        datos_filtrados = data[(data[:, 0] == year) & (data[:, 1] == month) & (data[:, 2] == day)]

        if len(datos_filtrados) == 0:
            print("No se encontraron datos para la fecha especificada")
            return

        #informacion relacionados con la temperatura (promedio en °C) y la radiación solar global (GHI máxima en W/m2)
        temp_promedio = np.mean(datos_filtrados[:, 4])
        ghi_maximo = np.max(datos_filtrados[:, 5])
        print(f"Temperatura promedio: {temp_promedio:.2f}°C")
        print(f"GHI máximo: {ghi_maximo:.2f} W/m²")

        return datos_filtrados

    except FileNotFoundError:
        print(f"No se encontró el archivo {filepath}")
    except IndexError:
        print("El archivo no tiene el formato esperado")
    except Exception as e:
        print("Error inesperado")
        print(f"Error específico: {e}")

# Paso 10: Pruebas finales
if __name__ == "__main__":
    # Prueba con una fecha que existe en los datos
    print("Prueba 1: Fecha existente")
    filter_data_final('GHI_Temp_Daily_Hourly_2024.csv', 2024, 1, 1)

    # Prueba con una fecha que no existe (30 de febrero)
    print("\nPrueba 2: Fecha inexistente")
    filter_data_final('GHI_Temp_Daily_Hourly_2024.csv', 2025, 2, 30)

    # Prueba con un nombre de archivo que no existe para verificar el manejo de errores
    print("\nPrueba 3: Archivo inexistente")
    filter_data_final('archivo_inexistente.csv', 2024, 1, 1)

    # Prueba con al menos 2 fechas diferentes válidas
    print("\nPrueba 4: Primera fecha válida")
    filter_data_final('GHI_Temp_Daily_Hourly_2024.csv', 2024, 6, 15)
    print("\nPrueba 4: Segunda fecha válida")
    filter_data_final('GHI_Temp_Daily_Hourly_2024.csv', 2024, 10, 8)

(8785, 6)
Numero total de filas: 8785
Numero total de columnas: 6
[[2.024e+03 1.000e+00 1.000e+00 0.000e+00 2.730e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 1.000e+00 2.680e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 2.000e+00 2.640e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 3.000e+00 2.610e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 4.000e+00 2.590e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 5.000e+00 2.560e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 6.000e+00 2.540e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 7.000e+00 2.520e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 8.000e+00 2.510e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 9.000e+00 2.490e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 1.000e+01 2.490e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 1.100e+01 2.550e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 1.200e+01 2.740e+01 8.000e+01]
 [2.024e+03 1.000e+00 1.000e+00 1.300e+01 2.940e+01 2.970e+02]
 [2.024e+03 1.000e+00 1.000e+00 1.400e+01 3.140e+01 